services:
  - type: web
    name: refugio-backend
    env: docker
    plan: starter
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 8080
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar 